// --- TYPES CHO LUỒNG AUTHENTICATION ---
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_AUTH_ROLE = "SET_AUTH_ROLE";
export const SET_VERIFYING_INFO = "SET_VERIFYING_INFO";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";

// --- TYPES CHO QUẢN LÝ / CHAT NHÂN VIÊN ---
export const SET_EMPLOYEE_STORE_LIST = "SET_EMPLOYEE_STORE_LIST";
export const SET_EMPLOYEE_ACTION_LOADING = "SET_EMPLOYEE_ACTION_LOADING";
export const SET_CHAT_CURRENT_SELECTED_EMPLOYEE = "SET_CHAT_CURRENT_SELECTED_EMPLOYEE";